kind: ConfigMap
apiVersion: v1
metadata:
  name: api-users
data:
  application.yaml: |-
    users:
      message: Welcome to Users Service!

    endpoints.trace.sensitive: false

    backend:
      ribbon:
        eureka.enabled: false
        client.enabled: true
