kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-users
spec:
  selector:
    matchLabels:
      app: api-users
  replicas: 1
  template:
    metadata:
      labels:
        app: api-users
    spec:
      containers:
        - name: api-users
          image: api-users:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: api-users
spec:
  type: NodePort
  selector:
    app: api-users
  ports:
      - port: 8080
        targetPort: 8080
        nodePort: 32001
