kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-carts
spec:
  selector:
    matchLabels:
      app: api-carts
  replicas: 1
  template:
    metadata:
      labels:
        app: api-carts
    spec:
      containers:
        - name: api-carts
          image: api-carts:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: api-carts
spec:
  type: NodePort
  selector:
    app: api-carts
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32002
